apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-it19513188
  name: ctse-it19513188
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ctse-it19513188
status:
  loadBalancer: {}