apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-assignment-it19513188
  name: ctse-assignment-it19513188
spec:
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: ctse-assignment-it19513188
status:
  loadBalancer: {}